name: Copy Wiki To Github Pages

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'This action will keep Github Pages in sync with the Wiki (which is source).'
        required: true
        default: 'User triggered'

jobs:
  copy-wiki:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Checkout wiki
      run: |
        git clone https://github.com/WebOfTrust/WOT-terms.wiki.git wiki

    - name: Move wiki to subdirectory
      run: |
        mkdir -p docs/04_glossary  # Create the directory if it doesn't exist
        rsync -a wiki/ docs/04_glossary/  # Synchronize wiki contents to /docs/04_glossary/

    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Automatically copied wiki to /docs/04_glossary/"
        git push
