name: Copy files from remote repo test 3

on:
  # schedule:
  #   - cron: '0 * * * *'
  # workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout remote repo
        uses: actions/checkout@v2
        with:
          repository: trustoverip/acdc
          ref: main
          path: /docs/acdc-test
