name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
  workflow_dispatch:

jobs:
  # create-preview-md:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v2

  #     - name: Run Node.js script
  #       run: node node_scripts/import-google-sheet/index.js
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    # needs: ['create-preview-md']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      # Fetches data from WOT-terms (Google sheet) and generates an overview file that takes all the terms and their definitions and puts them into a single file. 
      - name: Import Google Sheet “WOT-terms”, tab “Terms-WOT-manage” data into markdown file
        run: node externalContentCarbonCopies/fetchTermsMetaData.js

      # - name: Fetch information for import Google Sheet “WOT-terms”, tab “LabelContent” data into markdown files
      #   run: node externalContentCarbonCopies/fetchExternalContentMetaData.js

      # - name: Import Google Sheet “WOT-terms”, tab “LabelContent” data into markdown files
      #   run: node externalContentCarbonCopies/fetchExternalContent.js

      # Clones the wiki
      - name: Checkout wiki
        run: |
          git clone https://github.com/WebOfTrust/WOT-terms.wiki.git wiki

      # Copies the wiki contents to the /docs/04_glossary/ directory
      - name: Copy Wiki To Docusaurus Glossary directory
        run: |
          mkdir -p docs/04_glossary  # Create the directory if it doesn't exist
          rsync -a wiki/ docs/04_glossary/  # Synchronize wiki contents to /docs/04_glossary/

      # Pushes the changes from the wiki into the repo 
      - name: Commit and push the changes coming from the wiki
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Automatically copied wiki to /docs/04_glossary/"
          git push
        
      # Builds the website so it is also visible in the KERISSE website
      - name: Build website
        run: npm run build

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./build
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
