name: Find broken links

on:
  schedule:
    - cron: '0 3 * * 1' # Every Monday at 3:00 PM
  workflow_dispatch:

jobs:
  findbrokenlinks:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: npm

      - name: Install dependencies
        run: npm ci
      

      ##############################
      # Find broken links
      ##############################

      - name: Find broken links
        env:
          GITHUB_ISSUE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node maintenance/findBrokenLinks.js

      - name: Commit and push if there are changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add -A
          # git diff --exit-code && exit 0  # Exit if no changes
          git commit -m "Auto-commit broken links report"
          git push
        continue-on-error: true  # Continue even if nothing to commit
      ##############################
