name: Scrape sites

on:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      # - name: Set up Node.js
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '19'

      - name: Install dependencies
        run: npm ci

      - name: Set environment variables
        run: |
          echo "TYPESENSE_ADMIN_API_KEY=${{ secrets.TYPESENSE_ADMIN_API_KEY }}" >> $GITHUB_ENV
          echo "TYPESENSE_HOST=${{ secrets.TYPESENSE_HOST }}" >> $GITHUB_ENV
          echo "TYPESENSE_COLLECTION_NAME=${{ secrets.TYPESENSE_COLLECTION_NAME }}" >> $GITHUB_ENV
        
      - name: Run Shell Script
        run: bash scrapers/main.sh